# Turn on the visual web management console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Lock down the database name so it stays constant on every reboot
spring.datasource.url=jdbc:h2:mem:taskmasterdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ensures our database tables show up cleanly in the console
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=truespring.application.name=backend
